#version 460

layout(push_constant) uniform CompositionPushConstants {
    vec4 selectedObjectColor;  // Color of the selected object
    vec4 outlineColor;         // RGBA highlight color
    uint outlineThickness;     // Thickness of the outline in pixels
} push;

// input images
layout(set = 0, binding = 0) uniform sampler2D sceneColor;     // Scene color buffer
layout(set = 0, binding = 1) uniform sampler2D selectionMask;  // Mask of selected object
layout(set = 0, binding = 2) uniform sampler2D objectIds;      // Object Ids as Colors

// output image
layout(set = 0, binding = 3) uniform writeonly image2D outputImage;

// workgroup size
layout(local_size_x = 16, local_size_y = 16) in;

float fetchMask(ivec2 coord, ivec2 imageExtent) {
    // clamp to image boundaries
    ivec2 clamped = clamp(coord, ivec2(0), imageExtent - 1);
    return texelFetch(selectionMask, clamped, 0).r;
}

vec4 fetchSceneColor(ivec2 coord, ivec2 imageExtent) {
    ivec2 clamped = clamp(coord, ivec2(0), imageExtent - 1);
    return texelFetch(sceneColor, clamped, 0);
}

vec4 fetchIdColor(ivec2 coord, ivec2 imageExtent) {
    ivec2 clamped = clamp(coord, ivec2(0), imageExtent - 1);
    return texelFetch(objectIds, clamped, 0);
}

vec4 shade_darker(vec4 color, float factor) {
    return vec4(color.rgb * factor, color.a);
}

void main() {
    ivec2 imageExtent = imageSize(outputImage);
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec3 invalidColorId = vec3(0.0, 0.0, 0.0);

    if (pixelCoord.x >= imageExtent.x || pixelCoord.y >= imageExtent.y) {
        return; // outside bounds
    }

    vec4 sceneColor = fetchSceneColor(pixelCoord, imageExtent);
    float maskValue = fetchMask(pixelCoord, imageExtent);

    // if we are inside the selected object, we return the scene color
    if (maskValue > 0.5) {
        imageStore(outputImage, pixelCoord, sceneColor);
        return;
    }

    int thickness = int(push.outlineThickness);

    // when outside the object, check neighboring pixels within the outline thickness 
    for (int y = -thickness; y <= thickness; y++) {
        for (int x = -thickness; x <= thickness; x++) {

            ivec2 neighborCoord = pixelCoord + ivec2(x, y);
            float neighborMaskValue = fetchMask(neighborCoord, imageExtent);

            if (neighborMaskValue > 0.5) {
                // We found a neighboring pixel that belongs to the selected object
                // so we draw the outline color here

                // if the outline neighbor is behind another object, we draw it darker
                vec4 nighborIdColor = fetchIdColor(neighborCoord, imageExtent);
                if (nighborIdColor != push.selectedObjectColor) {
                    imageStore(outputImage, pixelCoord, shade_darker(push.outlineColor, 0.5));
                    return;
                }

                // otherwise, draw the normal outline color
                imageStore(outputImage, pixelCoord, push.outlineColor);
                return;
            }
        }
    }

    // otherwise, keep the original scene color
    imageStore(outputImage, pixelCoord, sceneColor);
}
